{% set name = "cryptopp" %}
{% set version = "8.9.0" %}
{% set sha256 = "ab5174b9b5c6236588e15a1aa1aaecb6658cdbe09501c7981ac8db276a24d9ab" %}
{% set sha256_cmake = "191d69061c56602de1610ebf03b44dcf75636006e7e60ef8105bee6472ec0caf" %}

package:
  name: {{ name| lower }}
  version: {{ version }}

source:
  - fn: {{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
    url: https://github.com/weidai11/cryptopp/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
    sha256: {{ sha256 }}
  - folder: cryptopp-cmake
    fn: cmake-{{ name | upper }}-{{ version | replace('.', '_') }}.tar.gz
    url: https://github.com/abdes/cryptopp-cmake/archive/{{ name | upper }}_{{ version | replace('.', '_') }}.tar.gz
    sha256: {{ sha256_cmake }}
    patches:
      - 113.patch

build:
  number: 2
  run_exports: {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - cmake >=3.28
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -f ${PREFIX}/lib/libcryptopp.a      # [unix]
    - test -d ${PREFIX}/include/cryptopp       # [unix]
    - test -f ${PREFIX}/share/cmake/cryptopp/cryptoppConfig.cmake         # [unix]
    - test -f ${PREFIX}/share/cmake/cryptopp/cryptoppConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_LIB%\cryptopp.lib (exit 0) else (exit 1)   # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cryptopp\cryptoppConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\share\cmake\cryptopp\cryptoppConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://www.cryptopp.com
  license: BSL-1.0
  license_file: License.txt
  summary: A C++ Class Library of Cryptographic Schemes

extra:
  recipe-maintainers:
    - apmorton
    - SylvainCorlay
    - JohanMabille
